# /backend/.nixpacks.toml

# Setup phase: Install Python and pip
[phases.setup]
nixPkgs = ["python311", "pip"]

# Build phase: Install Python dependencies
[phases.build]
cmds = ["pip install -r requirements.txt"]

# Start phase: Run FastAPI app with Uvicorn
[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
