[phases.setup]
nixPkgs = ["python311", "nodejs_18"]

[phases.install]
cmds = [
  "python3 -m venv /app/venv",  # Create the virtual environment in /app/venv
  "/app/venv/bin/pip install --upgrade pip",  # Use absolute path for pip
  "/app/venv/bin/pip install -r requirements.txt"  # Use absolute path for pip
]

[phases.start]
cmds = [
  "/app/venv/bin/python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"  # Use absolute path for python
]
