[phases.setup]
nixPkgs = ["python311Full", "nodejs"]

[phases.install]
cmds = [
  "python3 -m venv /venv",
  "/venv/bin/python3 -m pip install --upgrade pip",
  "/venv/bin/python3 -m pip install -r requirements.txt",
  "ls /venv/bin",  # Debugging
  "ls /venv/lib/python3.11/site-packages",  # Debugging
  "npm ci"
]

[phases.start]
cmds = [
  "/venv/bin/python3 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
]
