[phases.install]
cmds = [
  "python3 -m venv ./venv",  # Create virtual environment if not created by shell.nix
  "./venv/bin/pip install --upgrade pip",  # Ensure pip is up-to-date
  "./venv/bin/pip install -r requirements.txt",  # Install dependencies in venv
  "./venv/bin/pip show uvicorn",
  "ls ./venv/bin",  # Check that the virtual environment's bin directory exists
  "ls ./venv/lib/python3.11/site-packages"  # Ensure installed packages are in the correct location
]

[phases.start]
cmds = [
  "./venv/bin/python3 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"  # Use venv python to run the app
]
