[phases.setup]
nixPkgs = ["python311", "nodejs"]

[phases.install]
cmds = [
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r requirements.txt",
  "npm ci"
]

[phases.start]
cmds = [
  "python3 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
]
