[phases.setup]
nixPkgs = ["python311", "nodejs"]

[phases.install]
cmds = [
  "python3 -m venv /venv",
  "/venv/bin/pip install --upgrade pip",
  "/venv/bin/pip install -r requirements.txt",
  "npm ci"
]

[phases.start]
cmds = [
  "/venv/bin/python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
]
