[phases.setup]
nixPkgs = ["python311", "nodejs_18"]

[phases.install]
cmds = [
  "pip3 install -r requirements.txt",
  "npm ci"
]

[phases.start]
cmds = [
  "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
]
